### ISSUE TITLE
App crash when JSON cannot be parsed correctly

### ISSUE THREAD

**Issue by kaoh** [mnbogner/RosterApp#2]
E.g this JSON (most likely a different format) https://github.com/LockeWatts/wh40k/blob/master/codex_chaos_space_marines.json is not supported. Also this one is not supported: https://github.com/rgmc4/warhammer_conquest_cards/blob/master/warhammer.conquest.40K.cards.json It should be catched and a hint of the supported format should be given.

**Comment by mnbogner** [comment]
Files not ending in ".codex.json" will be ignored and opening a file with an unsupported format will now show an error message.
